### ISSUE TITLE
build failed, please help

### ISSUE THREAD

**Issue by diablogatox** [bladecoder/bladecoder-adventure-engine#2]
:blade-engine:javadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':blade-engine:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'C:\Users\diablogatox\git-repos\bladecoder-adventure-engine\blade-engine\build\tmp\javadoc\javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by diablogatox** [comment]
my jdk version is :

**Comment by diablogatox** [comment]
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by bladecoder** [comment]
Fixed: In jdk 1.8 javadoc has become very strict and produces some errors that weren't before.

**Comment by diablogatox** [comment]
than you so much
