### ISSUE TITLE
Play sound during animation

### ISSUE THREAD

**Issue by johnrico2000** [bladecoder/bladecoder-adventure-engine#20]
Hi people,

I'm not quite sure if I'm doing something wrong, but I would like to play a sound file during an animation. Problem is the sound just doesn't get played. Background music for my scene works fine though.

To be more specific: I'm trying to play a sound for foot steps during the walk animation of my character. I tried several formats like MP3, OGG or WAV since in a game I've made myself based on libGDX some years ago I sometimes had trouble playing a sound files, too, and changing the encoding format sometimes helped. Though I have to admit it always worked on desktop PCs back then and problems occured only on Android devices. With Bladecoder Adventure Engine, however, I don't manage to play a sound along an anmimation on PC at all.

In my character's settings I created a sound in the Sounds tab and in the animation settings of my character's "right" walk animation I assigned the sound id in the input field labeled "Sound". The sound just doesn't get played. Since in the project's wiki the "sounds in animations" chapter is not complete yet, I'm not quite sure if the feature actually is meant to work yet. I justed wanted to check back to you on that topic.

Oh, by the way, I'm on release 0.8.10. Latest trunk version didn't start for me.

**Comment by bladecoder** [comment]
Hi,

Currently, sounds are not played for walk, stand or talk animations. I'll fix that for the next version.

Although, If you are using Spine for your animations, you can use spine events to play sounds.

Right now, latest trunk is unstable due to a big refactor in the engine model. You can use the 'old_model' branch.

Regards.

**Comment by johnrico2000** [comment]
Thanks for the info. Is there any time schedule for the next version to be released?

**Comment by bladecoder** [comment]
A new version has been released today. The game model is stored in JSON now, previously was XML. Previous games can not be loaded with this release. Backward compatibility lost.
