### ISSUE TITLE
Something went wrong while creating project

### ISSUE THREAD

**Issue by Ryogaag** [bladecoder/bladecoder-adventure-engine#22]
I tried to create a new project and it gave me this error:
Something went wrong while creating project
RuntimeException - Couldn't read resource 'gradle.properties'

Is it a known issue?

**Comment by bladecoder** [comment]
Ok, this was an error with the .gitignore. It is fixed now. You can run the fixed editor version from master like that:

$ git clone https://github.com/bladecoder/bladecoder-adventure-engine.git
$ cd bladecoder-adventure-engine
$ ./gradlew adventure-editor:run

Regards.

**Comment by bladecoder** [comment]
fixed in v0.9.2
