### ISSUE TITLE
Fallo detectado

### ISSUE THREAD

**Issue by LudosMultimedia** [bladecoder/bladecoder-adventure-engine#25]
Si añades un sprite (atlases) con sus correspondientes cuadros de animación, y en el apartado Animations eliminas una por una todas las animaciones (x) si vuelves a pulsar para eliminar no habiendo nada se cierra el editor pero la consola sigue activa

**Comment by LudosMultimedia** [comment]
He estado probando por curiosidad en los demás apartados y pasa lo mismo. Si tienes algo lo eliminas perfectamente, el problema es que el botón eliminar queda activo y si le vuelves a dar al no haber nada el programa crashea.

**Comment by bladecoder** [comment]
Solucionado y subido a master. Irá en la versión 0.9.5.
