### ISSUE TITLE
What 3d models can I import?

### ISSUE THREAD

**Issue by TheAdventist** [bladecoder/bladecoder-adventure-engine#26]
Just got it running, and had some CC0 props I want to test to add to my project.
It is an .blend file, but BcAE doesn't display what types of 3d models can be imported.

And I couldn't find it in the .md file.

So, what can I import?

**Comment by bladecoder** [comment]
Hi,

You have a 3d project example here:
https://github.com/bladecoder/bladecoder-adventure-tests/tree/master/adventure-test-3d

The 3d models must be in the **g3db** format. Here you have a tutorial how to convert any 3d model into g3db through Blender:
https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX

Hope it helps.

Regards,

Rafael.
