### ISSUE TITLE
Actions shared by all actors

### ISSUE THREAD

**Issue by Silvia-Peter** [bladecoder/bladecoder-adventure-engine#3]
Hi,

currently, I have the problem that when I create an unique action for an actor, then this action is shared among all the other actors. For example, I created a lookat action for the house with the text "a small house". When running the game, the text "a small house" appears when clicking on the house, but also when clicking at the gate.
I noticed the problem in version 0.8.0 and 0.8.1. Can you please look into this?

Thank you very much! And really great work!
Silvia

**Comment by bladecoder** [comment]
Hi Silvia,

You have to create the verb in the 'Actor' scope with the target actor
selected. I think that you have created the verb in the World scope. All
verbs in World scope are shared between actors and scenes.

Regards,

Rafael.

**Comment by Silvia-Peter** [comment]
Hi Rafael,

I am pretty sure that I had the target actor selected. I have tried it a few times with different actors selected like you did with the cutter in your video 'Adventure Creator Demo' (https://www.youtube.com/watch?v=D_XyT02NeU8).
However, the dialog that appeared each time looked like it was meant for the world scope. So I thought that maybe the click events of the buttons got mixed up or something.

Regards,
Silvia

**Comment by bladecoder** [comment]
Hi Silvia,

It works for me... Can you send me your project zipped (or an example
project) to see what is wrong?

Regards,

Rafael.

**Comment by Silvia-Peter** [comment]
Hi Rafael,

thanks again for the great support! This is a really cool project. 

Regards,
Silvia
