### ISSUE TITLE
Create a new game with 1.2.0 doesn't run

### ISSUE THREAD

**Issue by magicvince** [bladecoder/bladecoder-adventure-engine#30]
If I create a new game with 1.2.0 there's a running error.
If the same game was created with 1.1.1, it works and when I open it with 1.2.0, accepting the update for the game, it's run with 1.2.0 and I can add new actors and test again the game.

I think it's an error with creation of the atlas path in game properties (but i'm not a coder)

I'm running bladecoder editor with Linux Mint Debian (a jessie debian) using openjdk-8 (from backports)

**Comment by bladecoder** [comment]
Hi @magicvince!

Thank you for your report. I have created a new project with v1.2.0 in Windows and it runs well. I will test it on Linux this afternoon.

Cheers,

Rafael.

**Comment by bladecoder** [comment]
Fixed in v1.2.1

**Comment by magicvince** [comment]
Yes I've tried this week-end
Very very thanks
