### ISSUE TITLE
Error opening the venus project

### ISSUE THREAD

**Issue by silverslade** [bladecoder/bladecoder-adventure-engine#31]
Hola Rafael!
First of all: thanks for your hard work on Bladecoder Engine.
This is a very impressive software (I work in Java since the 1.1 version and I really appreciate the grail centered-vision)
I have found an issue: I can't open the "venus" project at all (the other example projects do)

These are the steps to replicate it, (building from the sources on Windows 10):

1) git clone https://github.com/bladecoder/bladecoder-adventure-engine.git
2) cd bladecoder-adventure-engine
3) gradlew build
4) gradlew run
5) open the "venus" project
6) get this error (and project won't load successfully)

Set version info in versions.properties
:blade-engine:compileJava UP-TO-DATE
:blade-engine:processResources UP-TO-DATE
:blade-engine:classes UP-TO-DATE
:blade-engine:jar
:blade-engine-spine-plugin:compileJava UP-TO-DATE
:blade-engine-spine-plugin:processResources UP-TO-DATE
:blade-engine-spine-plugin:classes UP-TO-DATE
:blade-engine-spine-plugin:jar
:adventure-editor:compileJava UP-TO-DATE
:adventure-editor:processResources
:adventure-editor:setVersion UP-TO-DATE
:adventure-editor:classes
:adventure-editor:run
ENGINE: Error loading action: org.bladecoder.venus.actions.scene2.GetBonaseraAction {}
:adventure-editor:run FAILED

Hasta pronto!
Alessandro

**Comment by bladecoder** [comment]
The **venus** project has some custom actions written in Java. The editor detects that and execs the command ```gradlew desktop:compileJava``` in the **venus** project.

Maybe you are executing the editor with the JRE and you need the JDK to compile.

Can you compile the custom actions manually to see if some error appears?

1. cd venus
2. gradlew desktop:compileJava

Also, the editor have an error console that appears pressing ```F1```. What is the log that appears in the console?

Ciao!
Rafa.

**Comment by silverslade** [comment]
Hola Rafael!
Ok now it works! Gracias.
I had to compile with "gradlew desktop:compileJava" first.
Then the Editor will load it correctly.

Gracias
Alessandro

**Comment by bladecoder** [comment]
Umm, the editor should have compiled the project automatically when it
detects that a custom action is used...I have to look at this to see what
happened.

Thanks!

**Comment by bladecoder** [comment]
I found the problem not compiling the custom actions and it's fixed now.
