### ISSUE TITLE
is code protection possible ?

### ISSUE THREAD

**Issue by yogib33r** [bladecoder/bladecoder-adventure-engine#36]
hello 

ok far to begin my adventure project with friends but i have a question: is it possible to protect the game ? i want to try to sell it later and i have no idea if your FANTASTIC  software makes possible to put a serial or something else :)
anyway thanx a lot for this pure great piece of sofware, it works perfectly and i can't wait some more to begin my project
regards

stéphane

**Comment by bladecoder** [comment]
Hi,

Are you talking about DRM or something like that?

Regards,

Rafael

**Comment by yogib33r** [comment]
hello Rafael :)
thanx a lot answering me.
yes why not ? just make possible to protect the game. 
ok just know i'm studing actually and no way to begin the game right now (till 9 moths to wait for) but your software is fantastic :) just know i'm fan of ^^
kindly regards to you
stéphane

**Comment by bladecoder** [comment]
Hi,

The engine doesn't have integrated DRM, but some platforms give tools to protect games easily.

For example, Steam can add DRM to your game when you release the game in the platform: https://partner.steamgames.com/doc/features/drm

iOS adds the DRM always when you upload the game to the store.

Also, it is not difficult to add a third party DRM library to the game created with the engine, but you need programming skills.

Regards,

Rafael

**Comment by yogib33r** [comment]
hello rafael and thanx a lot for your answer !
ok i will do as this :) your tool is wonderfull :)
thanx yet
