### ISSUE TITLE
Dialogs seems not to work properly

### ISSUE THREAD

**Issue by laxertu** [bladecoder/bladecoder-adventure-engine#38]
Hi!

I have been trying to setup a dialog with some verbs to be performed just after it. I selected wait option to true (the default one), and expected behavoiur would be such verbs have been run after dialog have terminated, but they run while dialog is taking place. Maybe that's a bug? I solved with some quite tricky setup by my side, but I was wandering if this is the expected behaviour

thanks a lot

**Comment by bladecoder** [comment]
The talkto action stablish the dialog to show and doesn't wait. To execute some actions after selecting an option, you need to specify the verb to execute inside the option, there is a 'verb' parameter when you create a dialog option.

Also, dialog options only shows when cutmode=false. This allows, for example, to hide the dialog options when executing the verb inside an option (setting cutmode=true) and then continue with the next option (setting cutmode=false).
