### ISSUE TITLE
Java 11 not supported by Gradle 4.6

### ISSUE THREAD

**Issue by RaphaelWimmer** [bladecoder/bladecoder-adventure-engine#39]
When a Java 11 JDK is installed, running `./gradlew build` results in the error message 

> Could not determine java version from '11'.

Upgrading to v4.7  (in `gradle/wrapper/gradle-wrapper.properties`) resulted in a failed build with the error message 

> Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().

Upgrading gradle to v4.10 allows the build to complete successfully.

See also https://github.com/gradle/gradle/pull/4759]

**Comment by perlun** [comment]
I am also seeing the "Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory()" error with Gradle 4.7. Will try updating to 4.10 since the bug is likely not present there any more.

**Comment by bladecoder** [comment]
Gradle has been updated to v4.10.2 in the v2.2.0 release.

Java 11 is working fine now.
