### ISSUE TITLE
Inconsistency detected when running on linux

### ISSUE THREAD

**Issue by alfem** [bladecoder/bladecoder-adventure-engine#45]
I downloaded the new 3.1.2 release zip file and run it on my Linux Mint 19.1 with openjre 11.0.3.

These messages shows up and then nothing:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/alfem/prog/bladecoder/adventure-editor-3.1.2/lib/lwjgl-2.9.2.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

**Comment by nenad** [comment]
To fix this, I've used Java 8 (openjdk-8). A simple workaround is to run `JAVA_HOME=/usr/lib/jvm/java-8-openjdk ./bin/adventure-editor`.

**Comment by alfem** [comment]
Thanks for the clue, but 3 years late :-)
