### ISSUE TITLE
Any way to disable anti aliasing?

### ISSUE THREAD

**Issue by LeadheadOnline** [bladecoder/bladecoder-adventure-engine#46]
For my first project, I'm working on a low res (114x64) pixel art game, and I was wondering if there was a way to disable anti aliasing? 
![image](https://user-images.githubusercontent.com/44615875/74887332-a6d5c680-5348-11ea-9d34-f7486d16aedd.png) 

All my pixel art is being scaled up to fullscreen perfectly fine, but it get's this horrible blur, unless I scale it up manually to 1920x1080, which of course drastically increases my file sizes.

Thanks a ton! This seems like the only engine I have a _chance_ of making something with!

**Comment by bladecoder** [comment]
Yes, choose the nearest filter when creating the atlases.

![image](https://user-images.githubusercontent.com/6229260/74913406-daecce00-53c0-11ea-9f9a-0b24e76d413e.png)
