### ISSUE TITLE
Changing players walking and standing animations mid scene?

### ISSUE THREAD

**Issue by LeadheadOnline** [bladecoder/bladecoder-adventure-engine#47]
Sorry to use this page to ask questions, but I was wondering if I could change the player characters walking and standing animations without transitioning to a different scene. Should I just make a new character actor and switch them out? If so, how can I make one actor disappear and another appear? Should I just use empty animations designed to hide them?

**Comment by bladecoder** [comment]
You don't need to change of actor to set a new standing and walking animations. Use the SetActorAttr action instead, see screenshot.

![image](https://user-images.githubusercontent.com/6229260/75138452-8b710f80-56ea-11ea-8ec1-2e66c7a5fd7a.png)
