### ISSUE TITLE
Idea: Support custom java code.

### ISSUE THREAD

**Issue by lines-of-codes** [bladecoder/bladecoder-adventure-engine#52]
I have an idea. To support external java code as a custom action.
I know this is a non-code game engine but It's okay to have an optional code.

**Comment by bladecoder** [comment]
This feature is included in the engine since the first release. Check the venus test project, inside the core folder, it uses some custom actions.

**Comment by lines-of-codes** [comment]
Oh really? Sorry, I didn't notice that.
