### ISSUE TITLE
ink files fail to compile (linux)

### ISSUE THREAD

**Issue by blurymind** [bladecoder/bladecoder-adventure-engine#57]
Hi, I got so interested in using ink with bladecoder that I added support for editing ink files as well as compiling them to json files directly in yarn editor
https://yarnspinnertool.github.io/YarnEditor/

I managed to get it there using the wasm port of inklecate.

Today I actually tried changing the example project's ink file, only to discover that when I playtest the game, nothing changes.
I discovered that there is a "Compile ink script" command, which requires me to point it to inklecate's folder.
Sure enough I did
![image](https://user-images.githubusercontent.com/6495061/140658687-c197923c-8a56-447e-9b6c-2bd8195c722b.png)
then i get this
![image](https://user-images.githubusercontent.com/6495061/140658705-1ef96dda-6ed7-40af-9679-f4ee59bec022.png)

There is no explanation why it failed. It doesnt fail when I do it with inky or yarn editor.

So I want to ask, can i bypass this altogether? The process of manually selecting and compiling them like that is just plain painful. I already have the means of compiling straight to json files, so can I just point bladecoder to the json files?

**Comment by blurymind** [comment]
Ok so, after compiling the file with yarn editor to json and dumping it in the modules folder, I was able to successfully load it in blade coder.

It looks like the wasm version of inklecate  in yarn editor is doing a better job of creating a compatible file than inky, which is strange.

Anyways I simple suggestion to improve this is instead of having this dialog obscure what is going on (it doesnt tell you why it fails when it does, while even yarn editor can do that now) - I suggest replacing it with a simple command to open the modules folder. Or at least a button that in the dialog that opens the modules folder where the json files are to be found ro something like that.

**Comment by bladecoder** [comment]
Hi, there is a console in the editor that gives you more details about the errors that happens in the editor or while you are testing your game. Just press F1 to show the console dialog in the editor.

Hope it helps you in the future to obtain the cause of the errors.

**Comment by blurymind** [comment]
Hi, thank you for the hint. I eventually ended up directly exporting a compiled json file to the modules folder. Bladecoder's interpreter seems to be really good!

Apart of animations, what other things can I set up from with the ink file? Can I set state of actors too? It would be awesome if this was documented somewhere :)

**Comment by bladecoder** [comment]
Hi, you can call all actions that appear in the action dialog in the
editor from Ink, even custom actions that you can create in Java for your
project.

I attach a screenshot of one of my dialogs so you can have an idea of how
it works.

[image: image.png]

**Comment by blurymind** [comment]
This is absolutely fantastic! :D Very nice work on the integration!

I am sort of wondering if I can make YarnEditor a bit nicer for working specifically with bladecoder targeted ink files

**Comment by blurymind** [comment]
@bladecoder is there a file somewhere in the project where I can find all of these commands in one place?
I might be able to add them as autocompletion to yarn editor when in ink mode - If i have some place to extract them from

**Comment by blurymind** [comment]
@bladecoder something like this can be made now
![bladeCoderSnippets](https://user-images.githubusercontent.com/6495061/141509657-3d135539-6a6e-4fac-a582-5abe5d11b9f7.gif)

but for each one I have to manually code it like this
![image](https://user-images.githubusercontent.com/6495061/141509740-a3a09206-13c4-4f6d-9545-b00a2bdb6775.png)

If there was some sort of a file I could use to generate them all...

**Comment by blurymind** [comment]
how does one do Goto: pos x and y?

**Comment by bladecoder** [comment]
This is the correct syntax:

> Goto: actor=Character, target=targetActor, pos=400_0

'pos' is relative to target if specified. It not specified it is an absolute position.

All position parameters works withe this syntax: param=xxxx_yyyy
